NAME = libftprintf.a

SRC = ft_atoi.c ft_isascii.c ft_isalnum.c ft_isalpha.c ft_bzero.c ft_isprint.c ft_isdigit.c ft_lstadd.c ft_lstdelone.c \
	ft_lstdel.c ft_lstiter.c ft_memalloc.c ft_lstnew.c ft_lstmap.c ft_itoa.c ft_memchr.c ft_memcpy.c ft_memccpy.c \
	ft_memdel.c ft_memcmp.c ft_putchar.c ft_putchar_fd.c ft_memmove.c ft_memset.c ft_putendl.c ft_putendl_fd.c ft_putnbr.c \
	ft_putnbr_fd.c ft_putstr.c ft_putstr_fd.c ft_strcat.c ft_strclr.c ft_strchr.c ft_strcmp.c ft_strcpy.c ft_strdel.c \
	ft_striter.c ft_striteri.c ft_strequ.c ft_strdup.c ft_strlen.c ft_strmap.c ft_strlcat.c ft_strjoin.c ft_strmapi.c \
	ft_strnequ.c ft_strncat.c ft_strncpy.c ft_strncmp.c ft_strnew.c ft_strrchr.c ft_strnstr.c ft_strstr.c ft_strsub.c \
	ft_toupper.c ft_tolower.c ft_strtrim.c ft_strsplit.c ft_itoa_base.c ft_uitoa_base.c \
	./ft_printf/ft_fill_s_arg.c ./ft_printf/ft_fill_s_arg_2.c ./ft_printf/ft_isprint.c ./ft_printf/ft_itoa.c \
	./ft_printf/ft_itoa_base.c ./ft_printf/ft_print_bad_arg.c ./ft_printf/ft_print_c.c ./ft_printf/ft_print_c_maj.c \
	./ft_printf/ft_print_d.c ./ft_printf/ft_print_d_maj.c ./ft_printf/ft_print_i.c ./ft_printf/ft_print_modulo.c \
	./ft_printf/ft_print_o.c ./ft_printf/ft_print_o_maj.c ./ft_printf/ft_print_p.c ./ft_printf/ft_print_s.c \
	./ft_printf/ft_print_s_maj.c ./ft_printf/ft_print_u.c ./ft_printf/ft_print_u_maj.c ./ft_printf/ft_print_x.c \
	./ft_printf/ft_print_x_maj.c ./ft_printf/ft_printf.c ./ft_printf/ft_putwchar.c \
	./ft_printf/ft_size_to_print.c ./ft_printf/ft_strlen.c \
	./ft_printf/ft_strndup.c ./ft_printf/ft_tab_functions.c ./ft_printf/ft_tmp_next.c ./ft_printf/ft_uitoa.c \
	./ft_printf/ft_uitoa_base.c ./ft_printf/ft_wstrdup.c ./ft_printf/ft_wstrlen.c



OBJ = ft_atoi.o ft_isascii.o ft_isalnum.o ft_isalpha.o ft_bzero.o ft_isprint.o ft_isdigit.o ft_lstadd.o ft_lstdelone.o \
	ft_lstdel.o ft_lstiter.o ft_memalloc.o ft_lstnew.o ft_lstmap.o ft_itoa.o ft_memchr.o ft_memcpy.o ft_memccpy.o \
	ft_memdel.o ft_memcmp.o ft_putchar.o ft_putchar_fd.o ft_memmove.o ft_memset.o ft_putendl.o ft_putendl_fd.o ft_putnbr.o \
	ft_putnbr_fd.o ft_putstr.o ft_putstr_fd.o ft_strcat.o ft_strclr.o ft_strchr.o ft_strcmp.o ft_strcpy.o ft_strdel.o \
	ft_striter.o ft_striteri.o ft_strequ.o ft_strdup.o ft_strlen.o ft_strmap.o ft_strlcat.o ft_strjoin.o ft_strmapi.o \
	ft_strnequ.o ft_strncat.o ft_strncpy.o ft_strncmp.o ft_strnew.o ft_strrchr.o ft_strnstr.o ft_strstr.o ft_strsub.o \
	ft_toupper.o ft_tolower.o ft_strtrim.o ft_strsplit.o ft_itoa_base.o ft_uitoa_base.o ft_atoi.o \
	ft_fill_s_arg.o ft_fill_s_arg_2.o ft_isprint.o ft_itoa.o ft_itoa_base.o ft_print_bad_arg.o ft_print_c.o ft_print_c_maj.o \
	ft_print_d.o ft_print_d_maj.o ft_print_i.o ft_print_modulo.o ft_print_o.o ft_print_o_maj.o ft_print_p.o ft_print_s.o \
	ft_print_s_maj.o ft_print_u.o ft_print_u_maj.o ft_print_x.o ft_print_x_maj.o ft_printf.o ft_putstr.o ft_putwchar.o \
	ft_size_to_print.o ft_strcpy.o ft_strdup.o ft_strlen.o ft_strndup.o ft_tab_functions.o ft_tmp_next.o ft_uitoa.o \
	ft_uitoa_base.o ft_wstrdup.o ft_wstrlen.o


$(NAME) :
	gcc -Werror -Wall -Wextra -c $(SRC) libftprintf.h
	ar rc $(NAME) $(OBJ) libftprintf.h
	ranlib $(NAME)

all : $(NAME)

clean :
	rm -f $(OBJ)

fclean : clean
	rm -f $(NAME)

re : fclean all